FROM rscohn2/bench.ubuntu.base
MAINTAINER Robert Cohn <Robert.S.Cohn@intel.com>

RUN apt-get install -y \
    python3-numpy \
    python3-scipy

RUN update-alternatives --set libblas.so.3 /usr/lib/atlas-base/atlas/libblas.so.3 \
    && update-alternatives --set liblapack.so.3 /usr/lib/atlas-base/atlas/liblapack.so.3
