# Latest Ubuntu LTS with intel python
FROM ubuntu:16.04
MAINTAINER Robert Cohn <Robert.S.Cohn@intel.com>

# ENV http_proxy http://proxy-us.intel.com:911
# ENV https_proxy http://proxy-us.intel.com:911

RUN apt-get update && apt-get install -y \
    libatlas3-base \
    libblas3 \
    libopenblas-base \
    numactl \
    python3 \
    python3-numpy \
    python3-scipy

WORKDIR /benchdata
