FROM ubuntu:16.04
MAINTAINER Robert Cohn <Robert.S.Cohn@intel.com>

RUN apt-get update && apt-get install -y \
    libatlas3-base \
    libblas3 \
    liblapack3 \
    libopenblas-base \
    numactl \
    python3 \
    python3-pip

RUN pip3 install --upgrade pip

WORKDIR /benchdata
