FROM ubuntu:16.04
MAINTAINER Robert Cohn <Robert.S.Cohn@intel.com>

# ENV http_proxy http://proxy-us.intel.com:911
# ENV https_proxy http://proxy-us.intel.com:911

RUN apt-get update && apt-get install -y \
    libopenblas-base \
    libatlas3-base \
    libblas3 \
    numactl \
    python3 \
    python3-pip

RUN pip3 install --upgrade pip

WORKDIR /benchdata
