FROM ubuntu:16.04
MAINTAINER Robert Cohn <Robert.S.Cohn@intel.com>

RUN apt-get update && apt install -y \
    libatlas3-base \
    libblas3 \
    liblapack3 \
    libopenblas-base \
    numactl \
    python \
    python-pip

RUN pip install --upgrade pip

WORKDIR /benchdata
